# -*- coding: utf-8 -*-
"""prac4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iiq2siDLHN8kLnhc0dMg8NDtj7WfOtl-
"""

import numpy as np

class Student:
    def __init__(self, name, marks, credits):
        self.name = name
        self.marks = np.array(marks)
        self.credits = np.array(credits)

    def gpa(self):
        return np.sum(self.marks * self.credits) / np.sum(self.credits)
def input_student():
    name = input("Name: ")
    marks = list(map(float, input("Marks: ").split()))
    credits = list(map(int, input("Credits: ").split()))
    return name, marks, credits
def output(students):
    students.sort(key=lambda x: x.gpa(), reverse=True)

    print("\n===== STUDENTS =====")

    for s in students:
        print(s.name, round(s.gpa(), 1))
import math
from input import input_student
from output import output
from domains.student import Student

students = []

n = int(input("Number of students: "))

for i in range(n):
    name, marks, credits = input_student()

    marks = [math.floor(x * 10) / 10 for x in marks]

    students.append(Student(name, marks, credits))

output(students)