import pandas as pd
df = pd.read_csv('students.csv')
print(df.head())
print(df.shape)
print(df[['name', 'GPA']])
print(df[df['GPA'] >= 3.5])
print(df.sort_values('GPA', ascending=False))
print(df.groupby('major')['GPA'].mean())

s = pd.read_csv('students.csv')
c = pd.read_csv('scores.csv')
print(s.isnull().sum())
print(c.isnull().sum())
s = s.fillna(s.mean(numeric_only=True))
c = c.fillna(c.mean(numeric_only=True))
df = s.merge(c, on='student_id')
df['average'] = df[['python', 'math', 'database']].mean(axis=1)
print(df.nlargest(5, 'average'))
print(df.groupby('major')['average'].mean())
